### ISSUE TITLE
Page in README.md not properly rendered

### ISSUE THREAD

**Issue by za** [HackTricks-wiki/hacktricks-cloud#94]
Hi,

It seems the page in `README.md` is no properly rendered.

![Screenshot 2024-10-14 150301](https://github.com/user-attachments/assets/281ea1b0-c201-4233-a4d9-e22b8b756221)

```
{% content-ref url
{% hint
```

**Comment by carlospolop** [comment]
Markdown is written to be rendered in https://cloud.hacktricks.xyz/ not in github

**Comment by za** [comment]
Noted 📝
